- name: "Silence OS develop"
  hosts: 127.0.0.1 
  connection: local 
  tasks:

     - name: "Get poky" 
       git:
        repo: git://git.yoctoproject.org/poky
        version: langdale
        dest: "{{TOP_SRCDIR}}/poky"

     - name: "Get meta-openembedded"
       git:
        repo: git://git.openembedded.org/meta-openembedded
        version: langdale
        dest: "{{TOP_SRCDIR}}/meta-openembedded"

     - name: "Get meta-raspberrypi"
       git:
        repo: git://git.yoctoproject.org/meta-raspberrypi
        version: master
        dest: "{{TOP_SRCDIR}}/meta-raspberrypi"

     - name: "Get meta-silence"
       git:
        repo: https://github.com/gscigala/meta-silence.git
        version: develop
        dest: "{{TOP_SRCDIR}}/meta-silence"
